---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: pocketbase
  name: pvc-pocketbase-file
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-client
  resources:
    requests:
      storage: 1Gi
