apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: pocketbase-backend
  name: pocketbase-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pocketbase-backend
  serviceName: pocketbase-backend
  template:
    metadata:
      labels:
        app: pocketbase-backend
    spec:
      containers:
      - name: pocketbase-backend
        image: registry.tino.sh/pocketbase-app
        volumeMounts:
        - name: db-file
          mountPath: /srv/pb_data
        resources:
          requests:
            memory: "50Mi"
            cpu: "30m"
          limits:
            memory: "64Mi"
            cpu: "100m"
#        readinessProbe:
#          httpGet:
#            path: /
#            port: 8090
#          initialDelaySeconds: 2
#          periodSeconds: 30
#          failureThreshold: 3
#        livenessProbe:
#          httpGet:
#            path: /
#            port: 8090
#          initialDelaySeconds: 5
#          periodSeconds: 20
#          failureThreshold: 2
      volumes:
      - name: db-file
        persistentVolumeClaim:
          claimName: pvc-pocketbase-file
