apiVersion: skaffold/v1
kind: Config
build:
  artifacts:
  - image: registry.tino.sh/pocketbase-app
    context: ../../
    docker:
      target: app
  - image: registry.tino.sh/pocketbase-proxy
    context: ../../
    docker:
      target: proxy
deploy:
  kustomize: {}
